name: Deploy
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - run: npm install
      - run: npm run generate
        env:
          BASE_URL: https://staging.projectceleste.com
      - run: rm dist/README.md
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Delete old files
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ vars.DEPLOY_PORT }}
          script: |
            cd ${{ vars.DEPLOY_TARGET_STAGING }}
            rm -rf * .nojekyll
      - name: Upload files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ vars.DEPLOY_PORT }}
          strip_components: 1
          source: "dist"
          target: "${{ vars.DEPLOY_TARGET_STAGING }}"
